# First print your name in the cell below then save this file. (or something nice about your instructor)

In [2]:
# In this cell print your name 

print("Yeasin Arafat Riyad")

Yeasin Arafat Riyad

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [3]:
%pip install pandas


import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

# Load in the data file using `pd.read_csv()`

In [7]:
df = pd.read_csv("data/listings.csv")

print(df)

             id                                               name    host_id  \
0          2595                              Skylit Midtown Castle       2845
1          3831  Whole flr w/private bdrm, bath & kitchen(pls r...       4869
2          5121                                    BlissArtsSpace!       7356
3          5136           Spacious Brooklyn Duplex, Patio + Garden       7378
4          5178                   Large Furnished Room Near B'way　       8967
...         ...                                                ...        ...
46522  44807522         Designer Gramercy Studio Townhouse by UNSQ   12941925
46523  44807786  Cozy & comfy apt in the heart of Inwood Manhattan  284790520
46524  44811717  Comfortable safe environment 24hr security camera  362453686
46525  44814944                 Upper West Side studio 86th Street    4039777
46526  44818009  5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN   48098268

         host_name neighbourhood_group       neighbourhood  latitude  \
0         Jennifer           Manhattan             Midtown  40.75362
1      LisaRoxanne            Brooklyn        Clinton Hill  40.68514
2            Garon            Brooklyn  Bedford-Stuyvesant  40.68688
3          Rebecca            Brooklyn         Sunset Park  40.66120
4         Shunichi           Manhattan      Hell's Kitchen  40.76489
...            ...                 ...                 ...       ...
46522        Brian           Manhattan            Gramercy  40.73433
46523        Salar           Manhattan  Washington Heights  40.85820
46524       Nicole            Brooklyn       East Flatbush  40.65399
46525     Fernando           Manhattan     Upper West Side  40.78731
46526       Marina            Brooklyn           Gravesend  40.59945

       longitude        room_type  price  minimum_nights  number_of_reviews  \
0      -73.98377  Entire home/apt    175               3                 48
1      -73.95976  Entire home/apt     75               1                340
2      -73.95596     Private room     60              29                 50
3      -73.99423  Entire home/apt    175              14                  1
4      -73.98493     Private room     65               2                473
...          ...              ...    ...             ...                ...
46522  -73.98383  Entire home/apt    145               7                  0
46523  -73.92733  Entire home/apt     87               6                  0
46524  -73.93287     Private room     59               3                  0
46525  -73.97029  Entire home/apt     80              30                  0
46526  -73.98209     Private room     66               1                  0

      last_review  reviews_per_month  calculated_host_listings_count  \
0      2019-11-04               0.37                               2
1      2020-08-01               4.75                               1
2      2019-12-02               0.37                               1
3      2014-01-02               0.01                               1
4      2020-03-15               3.44                               1
...           ...                ...                             ...
46522         NaN                NaN                               1
46523         NaN                NaN                               2
46524         NaN                NaN                               1
46525         NaN                NaN                               1
46526         NaN                NaN                               1

       availability_365
0                   365
1                   265
2                   365
3                   295
4                   340
...                 ...
46522               164
46523                85
46524                90
46525               113
46526                38

[46527 rows x 16 columns]

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [8]:
# 1. How many listings are there with a price less than 100?
cheap_listings = df[df['price'] < 100]

print(cheap_listings)

             id                                               name    host_id  \
1          3831  Whole flr w/private bdrm, bath & kitchen(pls r...       4869
2          5121                                    BlissArtsSpace!       7356
4          5178                   Large Furnished Room Near B'way　       8967
5          5203                 Cozy Clean Guest Room - Family Apt       7490
8          5803     Lovely Room 1, Garden, Best Area, Legal rental       9744
...         ...                                                ...        ...
46520  44804690    Cozy place, peaceful,  friendly and affordable.  362419479
46523  44807786  Cozy & comfy apt in the heart of Inwood Manhattan  284790520
46524  44811717  Comfortable safe environment 24hr security camera  362453686
46525  44814944                 Upper West Side studio 86th Street    4039777
46526  44818009  5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN   48098268

         host_name neighbourhood_group       neighbourhood  latitude  \
1      LisaRoxanne            Brooklyn        Clinton Hill  40.68514
2            Garon            Brooklyn  Bedford-Stuyvesant  40.68688
4         Shunichi           Manhattan      Hell's Kitchen  40.76489
5        MaryEllen           Manhattan     Upper West Side  40.80178
8           Laurie            Brooklyn         South Slope  40.66829
...            ...                 ...                 ...       ...
46520         Elia              Queens          St. Albans  40.69980
46523        Salar           Manhattan  Washington Heights  40.85820
46524       Nicole            Brooklyn       East Flatbush  40.65399
46525     Fernando           Manhattan     Upper West Side  40.78731
46526       Marina            Brooklyn           Gravesend  40.59945

       longitude        room_type  price  minimum_nights  number_of_reviews  \
1      -73.95976  Entire home/apt     75               1                340
2      -73.95596     Private room     60              29                 50
4      -73.98493     Private room     65               2                473
5      -73.96723     Private room     75               2                118
8      -73.98779     Private room     88               4                180
...          ...              ...    ...             ...                ...
46520  -73.77104     Private room     44               1                  0
46523  -73.92733  Entire home/apt     87               6                  0
46524  -73.93287     Private room     59               3                  0
46525  -73.97029  Entire home/apt     80              30                  0
46526  -73.98209     Private room     66               1                  0

      last_review  reviews_per_month  calculated_host_listings_count  \
1      2020-08-01               4.75                               1
2      2019-12-02               0.37                               1
4      2020-03-15               3.44                               1
5      2017-07-21               0.89                               1
8      2020-03-18               1.31                               3
...           ...                ...                             ...
46520         NaN                NaN                               1
46523         NaN                NaN                               2
46524         NaN                NaN                               1
46525         NaN                NaN                               1
46526         NaN                NaN                               1

       availability_365
1                   265
2                   365
4                   340
5                     0
8                   344
...                 ...
46520               161
46523                85
46524                90
46525               113
46526                38

[22778 rows x 16 columns]

In [14]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.

df_bk = df[df['neighbourhood_group'] == 'Brooklyn']
print(df_bk.shape)

(10473, 16)

In [13]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.

df = df[(df['neighbourhood_group'] == 'Brooklyn') & (df['price'] < 100)]
print(df.shape[0])

10473

In [12]:
name_list = ['Michael', 'David', 'John', 'Daniel']

filtered_df = df[df['host_name'].isin(name_list)]
print(filtered_df.shape[0])

230

In [15]:
df['adjusted_price'] = df['price']
df.loc[df['neighbourhood'] == 'Williamsburg', 'adjusted_price'] += 100

df[['neighbourhood', 'price', 'adjusted_price']].head()

         neighbourhood  price  adjusted_price
1         Clinton Hill     75              75
2   Bedford-Stuyvesant     60              60
8          South Slope     88              88
21  Bedford-Stuyvesant     70              70
22         South Slope     88              88

In [16]:
total = len(df)

private_pct = (df['room_type'] == 'Private room').sum() / total * 100
shared_pct = (df['room_type'] == 'Shared room').sum() / total * 100

print(private_pct)
print(shared_pct)

76.52057672109234
2.7785734746490975

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [17]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
df.groupby('neighbourhood_group').size()

neighbourhood_group
Brooklyn    10473
dtype: int64

In [18]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups.
df.groupby('neighbourhood_group')['price'].mean()

neighbourhood_group
Brooklyn    61.819249
Name: price, dtype: float64

In [19]:
# 2.5. Using `groupby`, find the mean price for each room_type.
df.groupby('room_type')['price'].mean()

room_type
Entire home/apt    80.743530
Hotel room         37.250000
Private room       57.527078
Shared room        39.632302
Name: price, dtype: float64

In [20]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups.
df.groupby('neighbourhood_group')['price'].agg(['min', 'max'])

                     min  max
neighbourhood_group
Brooklyn               0   99

In [21]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.
df.groupby(['neighbourhood_group', 'room_type'])['price'].mean()

neighbourhood_group  room_type
Brooklyn             Entire home/apt    80.743530
                     Hotel room         37.250000
                     Private room       57.527078
                     Shared room        39.632302
Name: price, dtype: float64

In [22]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.
df.groupby(['neighbourhood_group', 'room_type'])['price'].agg(['count', 'min', 'max', 'mean', 'median', 'std'])

                                     count  min  max       mean  median  \
neighbourhood_group room_type
Brooklyn            Entire home/apt   2164   20   99  80.743530    85.0
                    Hotel room           4    0   99  37.250000    25.0
                    Private room      8014   10   99  57.527078    55.0
                    Shared room        291   15   99  39.632302    35.0

                                           std
neighbourhood_group room_type
Brooklyn            Entire home/apt  14.454876
                    Hotel room       47.436800
                    Private room     17.716431
                    Shared room      19.142267

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [24]:
prices = pd.read_csv("data/prices.csv")
n_listings = pd.read_csv("data/n_listings.csv")

prices.head()

  neighbourhood_group   mean_price
0               Bronx    92.751479
1            Brooklyn   120.225258
2           Manhattan   191.880466
3              Queens    99.754965
4       Staten Island   110.947214

In [27]:
print(prices.columns.tolist())
print(n_listings.columns.tolist())

['neighbourhood_group', ' mean_price']
['neighbourhood_group;n_listings']

In [ ]:
# 3. Save your joined csv as `joined.csv` into the data folder.
out_path = Path('Week-01-Pandas/data/joined.csv')
if not out_path.parent.exists():

    out_path = Path('data/joined.csv')
joined.to_csv(out_path, index=False)

In [ ]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`
joined_read_candidates = []
for base in [Path.cwd(), Path.cwd().parent]:

    joined_read_candidates.extend([joined_saved

        base / 'Week-01-Pandas' / 'data' / 'joined.csv',joined_saved = pd.read_csv(joined_file)

        base / 'data' / 'joined.csv',joined_file = next((p for p in joined_read_candidates if p.exists()), joined_read_candidates[0])

    ])])

joined_read_candidates.extend([    Path('data/joined.csv'),
    Path('Week-01-Pandas/data/joined.csv'),

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.